{% set name = "larch" %}
{% set version = "5.4.6" %}
{% set checksum = "2dc4389935f624496ea79e0f45eb1391959ff89fef4e223c9b3ba40c2a20f5ca" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jpn--/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  skip: true  # [py<36]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:

  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - llvm-openmp  # [osx]
    - cython >=0.29
    - numpy

  run:
    - python {{ python }}
    - ipython >=7.1
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy') }}
    - scipy >=1.1
    - pandas >=0.24
    - pytables >=3.4.4
    - blosc >=1.14.3
    - matplotlib-base >=3.0
    - networkx >=2.4
    - tqdm >=4.28.1
    - cloudpickle >=0.6.1
    - appdirs >=1.4
    - docutils >=0.13.1
    - jinja2 >=2.10
    - beautifulsoup4 >=4.6.3
    - lxml >=4.2.5
    - seaborn >=0.9.0
    - scikit-learn >=0.21
    - joblib
    - pytest >=4.0
    - xmle >=0.1.3
    - addict >=2.2.1
    - pyyaml
    - pillow
    - xlsxwriter
    - xlrd
    - pydot

test:
  source_files:
    - tests

  imports:
    - larch

  commands:
    - pytest ./tests

  requires:
    - pytest
    - pytest-regressions
    - geopandas

about:
  home: https://larch.newman.me
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Discrete Choice Modeling in Python

  description: |
    This is a tool for the estimation and application of logit-based discrete 
    choice models. It is designed to integrate with NumPy and Pandas to facilitate 
    fast processing of linear-in-parameters discrete choice models. 

  doc_url: https://larch.newman.me
  dev_url: https://github.com/jpn--/larch

extra:
  recipe-maintainers:
    - jpn--
