{% set name = "larch" %}
{% set version = "6.0.40" %}
{% set checksum = "2d24eb3d00346c94e95bc198adecf61c0bd21860171f3eb53f7e302a9b7531a4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy >=1.19
    - scipy >=1.1
    - pandas >=1.5
    - pyarrow
    - xarray
    - numba >=0.60
    - numexpr
    - filelock
    - dask
    - networkx
    - addicty
    - xmle >=0.1.25
    - rich
    - sparse
    - jinja2 >=2.10
    - xlsxwriter
    - zarr
    - tabulate
    - altair
    - vl-convert-python
    - pydot

test:
  source_files:
    - tests

  imports:
    - larch

  commands:
    - pytest ./tests

  requires:
    - python {{ python_min }}
    - pytest
    - pytest-regressions
    - geopandas
    - nbmake
    - jax
    - pytables
    - openmatrix
    - matplotlib
    - seaborn

about:
  home: https://larch.driftless.xyz
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Discrete Choice Modeling in Python

  description: |
    This is a tool for the estimation and application of logit-based discrete 
    choice models. It is designed to integrate with NumPy and Pandas to facilitate 
    fast processing of linear-in-parameters discrete choice models. 

  doc_url: https://larch.driftless.xyz
  dev_url: https://github.com/driftlesslabs/larch

extra:
  recipe-maintainers:
    - jpn--
